language: php

php:
  - 5.4
  - 5.5

before_script:
  - composer install -n
  - mysql -e 'CREATE DATABASE cavejadesk; CREATE USER cavejadesk@localhost; GRANT ALL ON cavejadesk.* TO cavejadesk@localhost'
  - app/console doctrine:migrations:migrate --no-interaction

script: bin/phpunit -c app
