language: php

php:
  - 5.4
  - 5.5

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install -n
  - mysql -e 'CREATE DATABASE cavejadesk'
  - app/console doctrine:migrations:migrate --no-interaction

script: bin/phpunit -c app
