caveja_money:
    resource: "@CavejaMoneyBundle/Resources/config/routing.yml"
    prefix:   /money

caveja_money_rest:
    type: rest
    resource: "@CavejaMoneyBundle/Resources/config/routing_rest.yml"
    prefix:   /money

caveja_desk:
    resource: "@CavejaDeskBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
